apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: controller-clusterrolebinding
roleRef:
  kind: ClusterRole
  name: controller-clusterrole
subjects:
- kind: ServiceAccount
  name: default
  namespace: production
