apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: controller-clusterrole
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["my.api.group.my.api.group"]
  resources: ["myappresources"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
