apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-deployment
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      containers:
      - name: controller
        image: ghcr.io/sumyann/k8s-controller:latest
