---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary
resources:
- deployment.yaml
- service.yaml
- namespace.yaml
- controller-deployment.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- myAppResource.yaml