# permissions for end users to view myappresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: myappresource-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-controller
    app.kubernetes.io/part-of: k8s-controller
    app.kubernetes.io/managed-by: kustomize
  name: myappresource-viewer-role
rules:
- apiGroups:
  - my.api.group.my.api.group
  resources:
  - myappresources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - my.api.group.my.api.group
  resources:
  - myappresources/status
  verbs:
  - get
