apiVersion: my.api.group.my.api.group/v1alpha1
kind: MyAppResource
metadata:
  labels:
    app.kubernetes.io/name: myappresource
    app.kubernetes.io/instance: myappresource-sample
    app.kubernetes.io/part-of: k8s-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: k8s-controller
  name: myappresource-sample
spec:
  # TODO(user): Add fields here
